# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Tomasz Marciniak]


In [13]:
import numpy as np

In [14]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

# Zadanie 1a
ceny_podwyżka = ceny * 1.05
print(ceny_podwyżka)


Kształt macierzy: (4, 3)
[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [15]:
# Zadanie 1b
print("Centrum:")
rabat_a = ceny * 0.90
print(rabat_a)
print("Galeria:")
rabat_b = ceny * 0.95
print(rabat_b)
print("Online:")
rabat_c = ceny * 0.85
print(rabat_c)


Centrum:
[[26.991 28.791 26.091]
 [44.991 47.691 43.191]
 [13.491 14.391 12.591]
 [89.991 94.491 85.491]]
Galeria:
[[28.4905 30.3905 27.5405]
 [47.4905 50.3405 45.5905]
 [14.2405 15.1905 13.2905]
 [94.9905 99.7405 90.2405]]
Online:
[[25.4915 27.1915 24.6415]
 [42.4915 45.0415 40.7915]
 [12.7415 13.5915 11.8915]
 [84.9915 89.2415 80.7415]]


In [16]:
# Zadanie 1c
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1 + marza)
print(koszt_zakupu)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [17]:
# Zadanie 1d
najtanszy_idx = ceny.argmin(axis=1)
najtanszy_sklepy = [sklepy[i] for i in najtanszy_idx]

# Łączymy produkt z najtańszym sklepem
for prod, sklep in zip(produkty, najtanszy_sklepy):
    print(f"Produkt {prod}: Najtaniej w {sklep}")

Produkt A: Najtaniej w Online
Produkt B: Najtaniej w Online
Produkt C: Najtaniej w Online
Produkt D: Najtaniej w Online


In [18]:
# Zadanie 2a
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")


Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [19]:
# Zadanie 2b — Stacking
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")


Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [20]:
# Zadanie 2c
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
macierz = sprzedaz_flat.reshape(6, 2)
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
srednia_per_produkt = macierz.mean(axis=1)
print(srednia_per_produkt)
# Wynik to tablica 6-elementowa (średnia dla każdego z 6 produktów)
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
macierz[:, 1] - macierz[:, 0]


[150. 225. 215. 170. 240. 225.]


array([100, 150, -70, 100, 140, -70])

In [21]:
# Zadanie 2d
import numpy as np

# Przykładowe dane wejściowe (12 miesięcy)
dane_flat = np.array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210])

# 1. Reshape na macierz kwartałów (4 kwartały po 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)

# 2. Spłaszczanie (powrót do 1D)
wektor = kwartaly.flatten()

# 3. Łączenie (dodanie 13-stego miesiąca)
kwartaly_final = np.concatenate([wektor, np.array([235])])

print("Po spłaszczeniu i dodaniu 13. miesiąca:")
print(kwartaly_final)


Po spłaszczeniu i dodaniu 13. miesiąca:
[100 110 120 130 140 150 160 170 180 190 200 210 235]


In [22]:
# Ćwiczenie 3
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])


In [23]:
# Zadanie 3a
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
print (f"Średnia: {pensje.mean()}") 
print (f"Mediana: {np.median(pensje)}")
print (f"Odchylenie: {pensje.std()}")
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
# 2. Wyświetl imiona osób zarabiających powyżej średniej
nazwiska = np.array(pracownicy)
print(nazwiska[pensje > pensje.mean()])

# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]
# 3. Wyświetl imiona osób zarabiających poniżej mediany

nazwiska = np.array(pracownicy)

mediana = np.median(pensje)

print(nazwiska[pensje < mediana])
# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)
# Rozstęp (cały zakres: od najniższej do najwyższej pensji)
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"Rozstęp: {rozstep}")
print(f"IQR: {iqr}")


Średnia: 6425.0
Mediana: 6050.0
Odchylenie: 1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900
IQR: 2200.0


In [ ]:
# Zadanie 3b
# 1. Obliczanie premii na podstawie ocen
premie = np.where(oceny >= 4.5, 2000, 
                  np.where(oceny >= 4.0, 1000, 0))

# 2. Obliczanie nowego wynagrodzenia (pensja + premia)
nowe_wynagrodzenia = pensje + premie

# 3. Wyświetlenie wyników dla wszystkich pracowników
print("Premie poszczególnych osób:", premie)
print("Nowe wynagrodzenia:", nowe_wynagrodzenia)

# 4. Kto dostał najwyższą premię?
# np.argmax(premie) zwraca indeks pierwszej osoby z najwyższą kwotą
indeks_najwyzszej_premii = np.argmax(premie)
pracownik_z_premia = np.array(pracownicy)[indeks_najwyzszej_premii]

print(f"\nNajwyższą premię ({premie.max()} zł) otrzymał/a: {pracownik_z_premia}")

Premie poszczególnych osób: [1000    0 2000 1000 2000    0 1000    0]
Nowe wynagrodzenia: [ 6500  7200  6800 10100  8300  4200  9500  5800]

Najwyższą premię (2000 zł) otrzymał/a: Ewa


In [ ]:
# Zadanie 3c

kolejnosc = np.argsort(pensje)[::-1]

print(f"{'Poz.':<5} | {'Imię':<10} | {'Pensja':<8} | {'Staż':<5}")
print("-" * 35)

for i, idx in enumerate(kolejnosc, 1):
    imie = pracownicy[idx]
    pensja = pensje[idx]
    lata_stazu = staz[idx]
    
    print(f"{i:<5} | {imie:<10} | {pensja:<8} | {lata_stazu:<5}")

Poz.  | Imię       | Pensja   | Staż 
-----------------------------------
1     | Marek      | 9100     | 15   
2     | Zofia      | 8500     | 12   
3     | Jan        | 7200     | 8    
4     | Kasia      | 6300     | 5    
5     | Tomek      | 5800     | 4    
6     | Anna       | 5500     | 3    
7     | Ewa        | 4800     | 2    
8     | Piotr      | 4200     | 1    


In [ ]:
# Zadanie 3d
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]

kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print(f"Korelacja Staż vs Pensja: {kor_staz_pensja:.4f}")
print(f"Korelacja Staż vs Ocena: {kor_staz_ocena:.4f}")


if abs(kor_staz_pensja) > abs(kor_staz_ocena):
    print("\nSilniejszy związek występuje między stażem a pensją.")
else:
    print("\nSilniejszy związek występuje między stażem a oceną.")

Korelacja Staż vs Pensja: 0.9879
Korelacja Staż vs Ocena: 0.0420

Silniejszy związek występuje między stażem a pensją.


In [40]:
# Zadanie 3e
# Zmiana kształtu cen na (4, 1)
ceny_kol = ceny_produktow.reshape(4, 1)

# Mnożenie macierzy przez kolumnę (Broadcasting)
przychod = sprzedaz * ceny_kol

print("Macierz przychodu (produkty x miesiące):")
print(przychod)
# Łączny przychód na produkt
suma_produkty = przychod.sum(axis=1)
najlepszy_produkt_idx = np.argmax(suma_produkty)
najlepszy_produkt_nazwa = produkty_nazwy[najlepszy_produkt_idx]

# Łączny przychód na miesiąc
suma_miesiace = przychod.sum(axis=0)
najlepszy_miesiac_idx = np.argmax(suma_miesiace)

print(f"\nNajlepszy produkt: {najlepszy_produkt_nazwa} ({suma_produkty.max()} zł)")
print(f"Najlepszy miesiąc (indeks): {najlepszy_miesiac_idx} (Suma: {suma_miesiace.max()} zł)")
# Podział na kwartały/półrocza (pierwsze 3 vs ostatnie 3 kolumny)
pierwsza_polowa = przychod[:, :3].sum()
druga_polowa = przychod[:, 3:].sum()

print(f"\nPrzychód - pierwsze 3 miesiące: {pierwsza_polowa} zł")
print(f"Przychód - ostatnie 3 miesiące: {druga_polowa} zł")

if druga_polowa > pierwsza_polowa:
    roznica = ((druga_polowa / pierwsza_polowa) - 1) * 100
    print(f"Trend: Wzrostowy! Sprzedaż wzrosła o {roznica:.2f}%")
else:
    print("Trend: Spadkowy.")

Macierz przychodu (produkty x miesiące):
[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]

Najlepszy produkt: Smartfon (1945000 zł)
Najlepszy miesiąc (indeks): 1 (Suma: 1154500 zł)

Przychód - pierwsze 3 miesiące: 2463950 zł
Przychód - ostatnie 3 miesiące: 2536500 zł
Trend: Wzrostowy! Sprzedaż wzrosła o 2.94%


In [41]:
# Zadanie 4
import numpy as np

# --- Krok 1 — Generowanie ---
np.random.seed(42)

# Wiek: rozkład normalny, średnia 35, std 10, min 18
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)

# Wydatki: rozkład normalny, średnia 500, std 200, min 0
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)

# Liczba wizyt: rozkład Poissona, lambda=5
wizyty = np.random.poisson(5, 100)

# --- Krok 2 — Analiza ---

### 1. Statystyki opisowe
def drukuj_statystyki(nazwa, dane):
    print(f"{nazwa:10} | Średnia: {dane.mean():.1f} | Mediana: {np.median(dane):.1f} | "
          f"Std: {dane.std():.1f} | Min: {dane.min():.1f} | Max: {dane.max():.1f}")

print("--- Statystyki opisowe ---")
drukuj_statystyki("Wiek", wiek)
drukuj_statystyki("Wydatki", wydatki)
drukuj_statystyki("Wizyty", wizyty)
print("-" * 30)

### 2 i 3. Korelacje
kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]

print(f"Korelacja Wiek vs Wydatki: {kor_wiek_wydatki:.3f}")
print(f"Korelacja Wizyty vs Wydatki: {kor_wizyty_wydatki:.3f}")
print("-" * 30)

### 4. Segmentacja klientów
sr = wydatki.mean()
sd = wydatki.std()

# Zagnieżdżony np.where
segmenty = np.where(wydatki > sr + sd, 'WYSOKI', 
           np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

### 5. Liczba klientów w segmentach
nazwy_segmentow, liczebnosc = np.unique(segmenty, return_counts=True)

print("Podział na segmenty:")
for nazwa, ilosc in zip(nazwy_segmentow, liczebnosc):
    print(f" - {nazwa}: {ilosc} klientów")

--- Statystyki opisowe ---
Wiek       | Średnia: 33.6 | Mediana: 33.0 | Std: 8.6 | Min: 18.0 | Max: 53.0
Wydatki    | Średnia: 504.5 | Mediana: 516.8 | Std: 189.8 | Min: 116.2 | Max: 1044.0
Wizyty     | Średnia: 4.9 | Mediana: 5.0 | Std: 2.2 | Min: 1.0 | Max: 11.0
------------------------------
Korelacja Wiek vs Wydatki: -0.120
Korelacja Wizyty vs Wydatki: -0.159
------------------------------
Podział na segmenty:
 - NISKI: 17 klientów
 - WYSOKI: 12 klientów
 - ŚREDNI: 71 klientów
