In [22]:
import numpy as np


In [23]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [24]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [27]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")


Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [28]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


## Atrybuty

In [29]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [30]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11 
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [31]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
sprzedaz_styczen = miesiace_sprzedaz[0]
print(f"sprzedaż_styczen:{sprzedaz_styczen}")

sprzedaż_styczen:120


In [32]:
sprzedaz_grudzien = miesiace_sprzedaz[-1]
print(f"sprzedaż_grudzień:{sprzedaz_grudzien}")

sprzedaż_grudzień:221


In [33]:
sprzedaz_Q1 = miesiace_sprzedaz[0:3]
print(f"sprzedaż_Q1:{sprzedaz_Q1}")

sprzedaż_Q1:[120 135  98]


In [34]:
sprzedaz_Q4 = miesiace_sprzedaz[9:12]
print(f"sprzedaż_Q4:{sprzedaz_Q4}")

sprzedaż_Q4:[143 198 221]


In [35]:
sprzedaz_co2 = miesiace_sprzedaz[::2]
print(f"sprzedaż_co2:{sprzedaz_co2}")

sprzedaż_co2:[120  98 167 201 156 198]


In [36]:
sprzedaz_od_tyłu = miesiace_sprzedaz[::-1]
print(f"sprzedaż_od_tyłu:{sprzedaz_od_tyłu}")

sprzedaż_od_tyłu:[221 198 143 156 178 201 189 167 142  98 135 120]


## Macierz 2D

In [37]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [38]:
A_Q2 = dane[0, 1]
print(A_Q2)

145


In [39]:
C = dane[2, :]
print(C)

[234 267 289]


In [40]:
Q1 = dane[:, 0]
print(Q1)

[120  89 234  56]


In [48]:
B_C_Q2_Q3 = dane[1:3, 1:3]
print(B_C_Q2_Q3)

[[102  95]
 [267 289]]


## Ćwiczenie 3


In [65]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1

In [66]:
# Średnia cena, najdroższy produkt, najtańszy produkt
print(f"Średnia cena to: {ceny.mean()}"),
print(f"Najwyższa cena to: {ceny.max()}")    ,
print(f"Najniższa cena to: {ceny.min()}"),
print(f"{ceny.argmax()}"), 
print(f"{ceny.argmin()}")

Średnia cena to: 1171.0
Najwyższa cena to: 3499
Najniższa cena to: 89
0
4


Zadanie 2

In [67]:
# Obliczanie wartości dla każdego produktu
wartosc_produktow = ceny * ilosci_magazyn

# Łączna wartość magazynu
laczna_wartosc = wartosc_produktow.sum()

print(f"Wartości poszczególnych pozycji: {wartosc_produktow}")
print(f"Łączna wartość magazynu: {laczna_wartosc:.2f} zł")


Wartości poszczególnych pozycji: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465.00 zł


Zadanie 3

In [75]:
cena_rabat = ceny * 0.85
print(f"Ceny po rabacie: {cena_rabat}")
cena_VAT = ceny * 1.23
print(f"Ceny z VAT: {cena_VAT}")
# Ile produktów kosztuje powyżej 1000 zł?
print(f"Ceny powyżej 1000: {(ceny > 1000).sum()}")



Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Ceny powyżej 1000: 4


Zadanie 4


In [90]:
# KROK 0: Konwersja listy nazw na obiekt numpy array, aby móc używać masek
nazwy_arr = np.array(nazwy)

maska_oceny = oceny_klientow >= 4.5
produkty_premium_nazwy = nazwy_arr[maska_oceny]
produkty_premium_ceny = ceny[maska_oceny]

maska_tanie = ceny < 200
maska_tanie_nazwy = nazwy_arr[maska_tanie]
maska_tanie_ilość = ilosci_magazyn[maska_tanie]

print("Produkty z wysoką oceną (>= 4.5):")
for n, c in zip(produkty_premium_nazwy, produkty_premium_ceny):
    print(f"- {n}: {c} zł")
    
print("Produkty tańsze niż 200zł:")
for n, i in zip(maska_tanie_nazwy, maska_tanie_ilość):
    print(f"- {n}: {i}")


Produkty z wysoką oceną (>= 4.5):
- Laptop: 3499 zł
- Smartfon: 2499 zł
- Słuchawki: 349 zł
- Monitor: 1499 zł
Produkty tańsze niż 200zł:
- Ładowarka: 312
- Mysz: 201


Zadanie 5

In [ ]:

nazwy_arr = np.array(nazwy)

wartosc_kazdego = ceny * ilosci_magazyn 
laczna_wartosc = wartosc_kazdego.sum()

maska_niski_stan = ilosci_magazyn < 30
produkty_braki = nazwy_arr[maska_niski_stan]

wartosc_brakow = wartosc_kazdego[maska_niski_stan].sum()
procent_wartosci = (wartosc_brakow / laczna_wartosc) * 100

print(f"Produkty wymagające zamówienia (< 30 szt.): {', '.join(produkty_braki)}")
print(f"Wartość tych produktów: {wartosc_brakow:,.2f} zł")
print(f"Stanowią one {procent_wartosci:.2f}% wartości całego magazynu.")

Produkty wymagające zamówienia (< 30 szt.): Laptop, Monitor
Wartość tych produktów: 86,962.00 zł
Stanowią one 15.83% wartości całego magazynu.


In [ ]:
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
okazje_nazwy = nazwy_arr[maska_okazja]
okazje_ceny = ceny[maska_okazja]

maska_wysoka_ocena = oceny_klientow >= 4.0
maska_niska_ocena = oceny_klientow < 4.0

srednia_wysokie = ceny[maska_wysoka_ocena].mean()
srednia_niskie = ceny[maska_niska_ocena].mean()

print("Produkty będące okazją (ocena >= 4.5 i cena < 1,000 zł):")
for n, c in zip(okazje_nazwy, okazje_ceny):
    print(f"- {n}: {c} zł")

print(f"\nŚrednia cena produktów z wysoką oceną (>= 4.0): {srednia_wysokie:.2f} zł")
print(f"Średnia cena produktów z niską oceną (< 4.0): {srednia_niskie:.2f} zł")

Produkty będące okazją (ocena >= 4.5 i cena < 1,000 zł):
- Słuchawki: 349 zł

Średnia cena produktów z wysoką oceną (>= 4.0): 1446.14 zł
Średnia cena produktów z niską oceną (< 4.0): 529.00 zł


## Ćwiczenie 4

In [98]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [99]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 64.9 ms
NumPy: 2.2 ms
NumPy jest 29× szybszy!

=== Suma (1,000,000 elementów) ===
Lista: 25.0 ms
NumPy: 0.6 ms
NumPy jest 43× szybszy!

=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 33.7 ms
NumPy: 2.5 ms
NumPy jest 14× szybszy!


## Wnioski z benchmarku
- NumPy jest **...×** szybszy w mnożeniu
- NumPy jest **...×** szybszy w sumowaniu
- NumPy jest **...×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list


Ćwiczenie 5: Commit na GitHub (5 min)